// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateText('txtTitle', { text: 'Ibex Leaderboard' });
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('lblMight', { text: 'Might' });
    CreateText('txtMight', { text: '...' });
    CreateText('lblExpand', { text: 'Expand' });
    CreateText('txtExpand', { text: 'Text' });
    CreateText('lblWealth', { text: 'Wealth' });
    CreateText('txtWealth', { text: 'Text' });
}
window.addEventListener('load', setupParts, false);
